### ISSUE TITLE
rtype/michelangeloderecha.png / rtype/UI.png

### ISSUE THREAD

**Issue by johndpope** [sliz3r/TMNT-Tribute#1]
is it possible to upload these assets and others?

**Comment by sliz3r** [comment]
what do you mean with upload these assets?

**Comment by sliz3r** [comment]
If you download the last release there you will found all the assets. https://github.com/sliz3r/TMNT-Tribute/releases/tag/v1.1

**Comment by johndpope** [comment]
Thanks
